### ISSUE TITLE
Feature request: add an entry for the desktop

### ISSUE THREAD

**Issue by ghost** [ralesi/alttab.ahk#6]
For something [EDIT: I meant _sometimes_, not something - sorry] that is what I want to go (back) to. Thanks. If you don't want to implement this, or there will be a delay, perhaps you could advise me on how to alter the code myself. I do know some Autohotkey. Thanks.

**Comment by lokeshgovindu** [comment]
@ACinnamonUserInUK: Could you please try this http://alttabalternative.sourceforge.net/ or https://github.com/lokeshgovindu/AltTabAlternative

If you want to implement your self, take a look at Display_List, ListView_Event subroutines.

Thanks.

**Comment by ghost** [comment]
@lokeshgovindu: Well, thank you, However, at least for the time being, I have returned to the built-in Windows switcher, albeit augmented with tweaks from the program WinAeroTweaker,
